DROP TABLE BLOOMER CASCADE CONSTRAINTS;
DROP TABLE HONEYBEE CASCADE CONSTRAINTS;
DROP TABLE LEAVEMEMBER CASCADE CONSTRAINTS;

DROP TABLE ENDPROJECT CASCADE CONSTRAINTS;
DROP TABLE CONPROJECT CASCADE CONSTRAINTS;
DROP TABLE PLANPROJECT CASCADE CONSTRAINTS;

DROP TABLE ENDPARLIST CASCADE CONSTRAINTS;
DROP TABLE CONPARLIST CASCADE CONSTRAINTS;
DROP TABLE PLANPARLIST CASCADE CONSTRAINTS;

DROP TABLE ENDSPONLIST CASCADE CONSTRAINTS;
DROP TABLE CONSPONLIST CASCADE CONSTRAINTS;
DROP TABLE PLANSPONLIST CASCADE CONSTRAINTS;

DROP TABLE ENDBRIEF CASCADE CONSTRAINTS;
DROP TABLE CONBRIEF CASCADE CONSTRAINTS;
DROP TABLE PLANBRIEF CASCADE CONSTRAINTS;

DROP TABLE ENDFAQ CASCADE CONSTRAINTS;
DROP TABLE CONFAQ CASCADE CONSTRAINTS;
DROP TABLE PLANFAQ CASCADE CONSTRAINTS;

DROP TABLE ENDEVENT CASCADE CONSTRAINTS;
DROP TABLE PLANEVENT CASCADE CONSTRAINTS;
DROP TABLE CONENDEVENT CASCADE CONSTRAINTS;
DROP TABLE CONEVENT CASCADE CONSTRAINTS;
DROP TABLE CONPLANEVENT CASCADE CONSTRAINTS;

DROP TABLE CONNOTICE CASCADE CONSTRAINTS;
DROP TABLE PLANNOTICE CASCADE CONSTRAINTS;

DROP TABLE CONPBOARD CASCADE CONSTRAINTS;
DROP TABLE CONFBOARD CASCADE CONSTRAINTS;
DROP TABLE PLANFBOARD CASCADE CONSTRAINTS;

DROP TABLE DELETEBOARD CASCADE CONSTRAINTS;

DROP TABLE CONNFILE CASCADE CONSTRAINTS;
DROP TABLE CONPFILE CASCADE CONSTRAINTS;
DROP TABLE CONFFILE CASCADE CONSTRAINTS;

DROP TABLE PLANNFILE CASCADE CONSTRAINTS;
DROP TABLE PLANFFILE CASCADE CONSTRAINTS;

DROP TABLE CONPCOMMENT CASCADE CONSTRAINTS;
DROP TABLE CONFCOMMENT CASCADE CONSTRAINTS;

DROP TABLE PLANFCOMMENT CASCADE CONSTRAINTS;

--멤버들-------------------------------------------------------------------------------

CREATE TABLE BLOOMER
(--프로젝트 참여자
    MBCODE VARCHAR2(11) PRIMARY KEY,
    EMAIL VARCHAR2(30) NOT NULL UNIQUE,
    PWD VARCHAR2(20) NOT NULL,
    NICK VARCHAR2(10)  NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    LEADER	VARCHAR2(1),
    ENROLLDAY DATE DEFAULT SYSDATE,
    LEAVEDAY DATE,
    CATEGORY1 VARCHAR2(30),
    CATEGORY2 VARCHAR2(30),
    CATEGORY3 VARCHAR2(30)
    
);
INSERT INTO BLOOMER VALUES('B1','1@1.com','admin','admin','admin',null,sysdate,null,null,null,null);
CREATE TABLE HONEYBEE
(--프로젝트 후원자
    MHCODE VARCHAR2(11) PRIMARY KEY,
    EMAIL VARCHAR2(30) NOT NULL UNIQUE,
    PWD VARCHAR2(20) NOT NULL,
    NICK VARCHAR2(10)  NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    ENROLLDAY DATE DEFAULT SYSDATE,
    LEAVEDAY DATE,
    CATEGORY1 VARCHAR2(30),
    CATEGORY2 VARCHAR2(30),
    CATEGORY3 VARCHAR2(30)
);
INSERT INTO HONEYBEE VALUES('H1','1@1.com','admin','admin','admin',sysdate,null,null,null,null);
--탈퇴-------------------------------------------------------------------------------

CREATE TABLE LEAVEMEMBER
(--탈퇴한 멤버 데이터 저장소
    ID VARCHAR2(20),
    MCODE VARCHAR2(11),
    NICK VARCHAR2(10),
    ENROLLDAY DATE,
    LEAVEDA DATE,
    FLAG VARCHAR2(1),
    CONSTRAINT PK_LEAVEMEM PRIMARY KEY(ID,MCODE)    
);

--프로젝트-------------------------------------------------------------------------------

CREATE TABLE ENDPROJECT
(
    PCODE VARCHAR2(13) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    CONTENT VARCHAR2(3000) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    GMONEY NUMBER NOT NULL,
    CMONEY NUMBER,
    LEADCODE VARCHAR2(11) NOT NULL,
    PERMIT VARCHAR2(1) NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_ENDPROMEM FOREIGN KEY(LEADCODE) REFERENCES  BLOOMER
);

CREATE TABLE CONPROJECT
(--진행중 프로젝트
    PCODE VARCHAR2(13) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    CONTENT VARCHAR2(3000) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    GMONEY NUMBER NOT NULL,
    CMONEY NUMBER,
    LEADCODE VARCHAR2(11) NOT NULL,
    PERMIT VARCHAR2(1) NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_CONPROMEM FOREIGN KEY(LEADCODE) REFERENCES  BLOOMER(MBCODE)
);

CREATE TABLE PLANPROJECT
(--예정된 프로젝트
    PCODE VARCHAR2(13) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    CONTENT VARCHAR2(3000) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    GMONEY NUMBER NOT NULL,
    CMONEY NUMBER,
    LEADCODE VARCHAR2(11) NOT NULL,
    PERMIT VARCHAR2(1) NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_PLANPROMEM FOREIGN KEY(LEADCODE) REFERENCES  BLOOMER(MBCODE)
);


--참여자리스트-------------------------------------------------------------------------------

CREATE TABLE ENDPARLIST
(--종료된 프로젝트의 참여자 리스트
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN1 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM1 FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM2 FOREIGN KEY(MCODE) REFERENCES  BLOOMER(MBCODE)
);

CREATE TABLE CONPARLIST
(--진행중 프로젝트의 참여자 리스트
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN2 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM3 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM4 FOREIGN KEY(MCODE) REFERENCES  BLOOMER(MBCODE)
);

CREATE TABLE PLANPARLIST
(--예정된 프로젝트의 참여자 리스트
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN3 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM5 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM6 FOREIGN KEY(MCODE) REFERENCES  BLOOMER(MBCODE)
);

--후원자리스트-------------------------------------------------------------------------------

CREATE TABLE ENDSPONLIST
(--종료된 프로젝트의 후원자 리스트
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN4 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM7 FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM8 FOREIGN KEY(MCODE) REFERENCES  HONEYBEE(MHCODE)
);

CREATE TABLE CONSPONLIST
(--진행중 프로젝트의 후원자 리스트
   PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN5 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM9 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM10 FOREIGN KEY(MCODE) REFERENCES  HONEYBEE(MHCODE)
);

CREATE TABLE PLANSPONLIST
(--예정된 프로젝트의 후원자 리스트
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN6 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM11 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM12 FOREIGN KEY(MCODE) REFERENCES  HONEYBEE(MHCODE)
);


--프로젝트요약-------------------------------------------------------------------------------

CREATE TABLE ENDBRIEF
(--종료된 프로젝트 요약
    PCODE VARCHAR2(13) PRIMARY KEY,
    CONTENT VARCHAR2(200) NOT NULL,
    MAINIMAGE VARCHAR2(100) NOT NULL,
    IMAGE1 VARCHAR2(100), 
    IMAGE2 VARCHAR2(100), 
    IMAGE3 VARCHAR2(100), 
    IMAGE4 VARCHAR2(100), 
    MAINVIDEO VARCHAR2(100) NOT NULL,
    VIDEO1 VARCHAR2(100),
    VIDEO2 VARCHAR2(100),
    CONSTRAINT FK_BRIEF1 FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE)
);

CREATE TABLE CONBRIEF
(--진행중 프로젝트 요약
    PCODE VARCHAR2(13) PRIMARY KEY,
    CONTENT VARCHAR2(200) NOT NULL,
    MAINIMAGE VARCHAR2(100) NOT NULL,
    IMAGE1 VARCHAR2(100), 
    IMAGE2 VARCHAR2(100), 
    IMAGE3 VARCHAR2(100), 
    IMAGE4 VARCHAR2(100), 
    MAINVIDEO VARCHAR2(100) NOT NULL,
    VIDEO1 VARCHAR2(100),
    VIDEO2 VARCHAR2(100),
    CONSTRAINT FK_BRIEF2 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE PLANBRIEF
(--예정된 프로젝트 요약
    PCODE VARCHAR2(13) PRIMARY KEY,
    CONTENT VARCHAR2(200) NOT NULL,
    MAINIMAGE VARCHAR2(100) NOT NULL,
    IMAGE1 VARCHAR2(100), 
    IMAGE2 VARCHAR2(100), 
    IMAGE3 VARCHAR2(100), 
    IMAGE4 VARCHAR2(100), 
    MAINVIDEO VARCHAR2(100) NOT NULL,
    VIDEO1 VARCHAR2(100),
    VIDEO2 VARCHAR2(100),
    CONSTRAINT FK_BRIEF3 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

--자주묻는질문-------------------------------------------------------------------------------

CREATE TABLE ENDFAQ
(--종료된 프로젝트 자주묻는질문
    PCODE VARCHAR2(13) PRIMARY KEY,
    EINDEX NUMBER NOT NULL UNIQUE,
    QUESTION VARCHAR2(100) NOT NULL,
    ANSWER VARCHAR2(100) NOT NULL, 
    CONSTRAINT FK_BRIEFFAQ1 FOREIGN KEY(PCODE) REFERENCES  ENDBRIEF(PCODE)
);

CREATE TABLE CONFAQ
(--진행중 프로젝트 자주묻는질문
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    QUESTION VARCHAR2(100) NOT NULL,
    ANSWER VARCHAR2(100) NOT NULL, 
    CONSTRAINT FK_BRIEFFAQ2 FOREIGN KEY(PCODE) REFERENCES CONBRIEF(PCODE)
);

CREATE TABLE PLANFAQ
(--종료된 프로젝트 자주묻는질문
    PCODE VARCHAR2(13) PRIMARY KEY,
    PINDEX NUMBER(1) NOT NULL UNIQUE,
    QUESTION VARCHAR2(100) NOT NULL,
    ANSWER VARCHAR2(100) NOT NULL, 
    CONSTRAINT FK_BRIEFFAQ3 FOREIGN KEY(PCODE) REFERENCES  PLANBRIEF(PCODE)
);

--이벤트---------------------------------------------------------------------------

CREATE TABLE ENDEVENT
(--종료된 이벤트
    PCODE VARCHAR2(13) PRIMARY KEY,
    EINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    CONSTRAINT FK_ENDEVENT FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE)
);

CREATE TABLE PLANEVENT
(--예정된 이벤트
    PCODE VARCHAR2(13) PRIMARY KEY,
    PINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL, 
    CONSTRAINT FK_PLANEVENT FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

CREATE TABLE CONENDEVENT
(--진행중 프로젝트의 종료된 이벤트
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL, 
    CONSTRAINT FK_CONEVENT1 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE CONEVENT
(--진행중 프로젝트의 진행중 이벤트
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL, 
    CONSTRAINT FK_CONEVENT2 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE CONPLANEVENT
(--진행중 프로젝트의 예정된 이벤트
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    CONSTRAINT FK_CONEVENT3 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

--공지사항---------------------------------------------------------------------------

CREATE TABLE CONNOTICE
(--진행중 프로젝트의 공지사항 게시판
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_NBOARDPRO FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE PLANNOTICE
(--예정된 프로젝트의 공지사항 게시판
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_NBOARDPRO2 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

--프로젝트게시판---------------------------------------------------------------------------

CREATE TABLE CONPBOARD
(--진행중 프로젝트의 프로젝트 게시판
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_BOARDPRO FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

--자유게시판---------------------------------------------------------------------------

CREATE TABLE CONFBOARD
(--진행중 프로젝트의 자유 게시판
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_FBOARDPRO FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE PLANFBOARD
(--예정된 프로젝트의 자유 게시판
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_FBOARDPRO2 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

--삭제된글---------------------------------------------------------------------------

CREATE TABLE DELETEBOARD
(--삭제된 게시글 임시보관
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL
);

--첨부파일---------------------------------------------------------------------------

CREATE TABLE CONNFILE
(--진행중 프로젝트 공지사항 첨부파일
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_CFILE1 FOREIGN KEY(BCODE) REFERENCES CONNOTICE(BCODE)
);

CREATE TABLE CONPFILE
(--진행중 프로젝트 프로젝트 게시판 첨부파일
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_CFILE2 FOREIGN KEY(BCODE) REFERENCES  CONPBOARD(BCODE)
);

CREATE TABLE CONFFILE
(--진행중 프로젝트 자유 게시판 첨부파일
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_CFILE3 FOREIGN KEY(BCODE) REFERENCES  CONFBOARD(BCODE)
);

--예정------------

CREATE TABLE PLANNFILE
(--예정된 프로젝트 공지사항 첨부파일
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_PFILE1 FOREIGN KEY(BCODE) REFERENCES  PLANNOTICE(BCODE)
);

CREATE TABLE PLANFFILE
(--예정된 프로젝트 자유 게시판 첨부파일
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_PFILE2 FOREIGN KEY(BCODE) REFERENCES  PLANFBOARD(BCODE)
);

--댓글---------------------------------------------------------------------------

CREATE TABLE CONPCOMMENT
(--진행중 프로젝트 프로젝트 게시판 댓글
    BCODE VARCHAR2(11),
    CINDEX NUMBER(6),
    TOPINDEX NUMBER(6),
    WRITER VARCHAR2(11),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(300),
    CONSTRAINT PK_COMEN1 PRIMARY KEY(BCODE, CINDEX),
    CONSTRAINT FK_COMEN1 FOREIGN KEY(BCODE) REFERENCES  CONPBOARD(BCODE)
);

CREATE TABLE CONFCOMMENT
(--진행중 프로젝트 자유 게시판 댓글
    BCODE VARCHAR2(11),
    CINDEX NUMBER(6),
    TOPINDEX NUMBER(6),
    WRITER VARCHAR2(11),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(300),
    CONSTRAINT PK_COMEN2 PRIMARY KEY(BCODE, CINDEX),
    CONSTRAINT FK_CCOMEN2 FOREIGN KEY(BCODE) REFERENCES  CONFBOARD(BCODE)
);

CREATE TABLE PLANFCOMMENT
(--예정된 프로젝트 자유 게시판 댓글
    BCODE VARCHAR2(11),
    CINDEX NUMBER(6),
    TOPINDEX NUMBER(6),
    WRITER VARCHAR2(11),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(300),
    CONSTRAINT PK_COMEN3 PRIMARY KEY(BCODE, CINDEX),
    CONSTRAINT FK_CCOMEN3 FOREIGN KEY(BCODE) REFERENCES  PLANFBOARD(BCODE)
);

COMMIT;

select *
from HONEYBEE;

select *
from BLOOMER;

update BLOOMER set LEADER='L' WHERE MBCODE='B2';
commit;