DROP TABLE BLOOMER CASCADE CONSTRAINTS;
DROP TABLE HONEYBEE CASCADE CONSTRAINTS;
DROP TABLE LEAVEMEMBER CASCADE CONSTRAINTS;

DROP TABLE ENDPROJECT CASCADE CONSTRAINTS;
DROP TABLE CONPROJECT CASCADE CONSTRAINTS;
DROP TABLE PLANPROJECT CASCADE CONSTRAINTS;

DROP TABLE ENDPARLIST CASCADE CONSTRAINTS;
DROP TABLE CONPARLIST CASCADE CONSTRAINTS;
DROP TABLE PLANPARLIST CASCADE CONSTRAINTS;

DROP TABLE ENDSPONLIST CASCADE CONSTRAINTS;
DROP TABLE CONSPONLIST CASCADE CONSTRAINTS;
DROP TABLE PLANSPONLIST CASCADE CONSTRAINTS;

DROP TABLE ENDBRIEF CASCADE CONSTRAINTS;
DROP TABLE CONBRIEF CASCADE CONSTRAINTS;
DROP TABLE PLANBRIEF CASCADE CONSTRAINTS;

DROP TABLE ENDFAQ CASCADE CONSTRAINTS;
DROP TABLE CONFAQ CASCADE CONSTRAINTS;
DROP TABLE PLANFAQ CASCADE CONSTRAINTS;

DROP TABLE ENDEVENT CASCADE CONSTRAINTS;
DROP TABLE PLANEVENT CASCADE CONSTRAINTS;
DROP TABLE CONENDEVENT CASCADE CONSTRAINTS;
DROP TABLE CONEVENT CASCADE CONSTRAINTS;
DROP TABLE CONPLANEVENT CASCADE CONSTRAINTS;

DROP TABLE CONNOTICE CASCADE CONSTRAINTS;
DROP TABLE PLANNOTICE CASCADE CONSTRAINTS;

DROP TABLE CONPBOARD CASCADE CONSTRAINTS;
DROP TABLE CONFBOARD CASCADE CONSTRAINTS;
DROP TABLE PLANFBOARD CASCADE CONSTRAINTS;

DROP TABLE DELETEBOARD CASCADE CONSTRAINTS;

DROP TABLE CONNFILE CASCADE CONSTRAINTS;
DROP TABLE CONPFILE CASCADE CONSTRAINTS;
DROP TABLE CONFFILE CASCADE CONSTRAINTS;

DROP TABLE PLANNFILE CASCADE CONSTRAINTS;
DROP TABLE PLANFFILE CASCADE CONSTRAINTS;

DROP TABLE CONPCOMMENT CASCADE CONSTRAINTS;
DROP TABLE CONFCOMMENT CASCADE CONSTRAINTS;

DROP TABLE PLANFCOMMENT CASCADE CONSTRAINTS;

--Î©§Î≤Ñ?ì§-------------------------------------------------------------------------------
desc BLOOMER;
CREATE TABLE BLOOMER
(--?îÑÎ°úÏ†ù?ä∏ Ï∞∏Ïó¨?ûê
    MBCODE VARCHAR2(11) PRIMARY KEY,
    ID VARCHAR2(20) NOT NULL,
    PWD VARCHAR2(20) NOT NULL,
    NICK VARCHAR2(10)  NOT NULL UNIQUE,
    EMAIL VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    LEADER	VARCHAR2(1),
    ENROLLDAY DATE DEFAULT SYSDATE,
    LEAVEDA DATE,
    CATEGORY1 VARCHAR2(30),
    CATEGORY2 VARCHAR2(30),
    CATEGORY3 VARCHAR2(30)
    
);

CREATE TABLE HONEYBEE
(--?îÑÎ°úÏ†ù?ä∏ ?õÑ?õê?ûê
    MHCODE VARCHAR2(11) PRIMARY KEY,
    ID VARCHAR2(20) NOT NULL,
    PWD VARCHAR2(20) NOT NULL,
    NICK VARCHAR2(10)  NOT NULL UNIQUE,
    EMAIL VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    ENROLLDAY DATE DEFAULT SYSDATE,
    LEAVEDA DATE,
    CATEGORY1 VARCHAR2(30),
    CATEGORY2 VARCHAR2(30),
    CATEGORY3 VARCHAR2(30)
);

--?Éà?á¥-------------------------------------------------------------------------------

CREATE TABLE LEAVEMEMBER
(--?Éà?á¥?ïú Î©§Î≤Ñ ?ç∞?ù¥?Ñ∞ ???û•?Üå
    ID VARCHAR2(20),
    MCODE VARCHAR2(11),
    NICK VARCHAR2(10),
    ENROLLDAY DATE,
    LEAVEDA DATE,
    FLAG VARCHAR2(1),
    CONSTRAINT PK_LEAVEMEM PRIMARY KEY(ID,MCODE)    
);

--?îÑÎ°úÏ†ù?ä∏-------------------------------------------------------------------------------

CREATE TABLE ENDPROJECT
(
    PCODE VARCHAR2(13) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    LEADCODE VARCHAR2(11) NOT NULL,
    CONSTRAINT FK_ENDPROMEM FOREIGN KEY(LEADCODE) REFERENCES  BLOOMER
);

CREATE TABLE CONPROJECT
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    LEADCODE VARCHAR2(11) NOT NULL,
    CONSTRAINT FK_CONPROMEM FOREIGN KEY(LEADCODE) REFERENCES  BLOOMER(MBCODE)
);

CREATE TABLE PLANPROJECT
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    LEADCODE VARCHAR2(11) NOT NULL,
    CONSTRAINT FK_PLANPROMEM FOREIGN KEY(LEADCODE) REFERENCES  BLOOMER(MBCODE)
);


--Ï∞∏Ïó¨?ûêÎ¶¨Ïä§?ä∏-------------------------------------------------------------------------------

CREATE TABLE ENDPARLIST
(--Ï¢ÖÎ£å?êú ?îÑÎ°úÏ†ù?ä∏?ùò Ï∞∏Ïó¨?ûê Î¶¨Ïä§?ä∏
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN1 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM1 FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM2 FOREIGN KEY(MCODE) REFERENCES  BLOOMER(MBCODE)
);

CREATE TABLE CONPARLIST
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò Ï∞∏Ïó¨?ûê Î¶¨Ïä§?ä∏
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN2 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM3 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM4 FOREIGN KEY(MCODE) REFERENCES  BLOOMER(MBCODE)
);

CREATE TABLE PLANPARLIST
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏?ùò Ï∞∏Ïó¨?ûê Î¶¨Ïä§?ä∏
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN3 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM5 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM6 FOREIGN KEY(MCODE) REFERENCES  BLOOMER(MBCODE)
);

--?õÑ?õê?ûêÎ¶¨Ïä§?ä∏-------------------------------------------------------------------------------

CREATE TABLE ENDSPONLIST
(--Ï¢ÖÎ£å?êú ?îÑÎ°úÏ†ù?ä∏?ùò ?õÑ?õê?ûê Î¶¨Ïä§?ä∏
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN4 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM7 FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM8 FOREIGN KEY(MCODE) REFERENCES  HONEYBEE(MHCODE)
);

CREATE TABLE CONSPONLIST
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò ?õÑ?õê?ûê Î¶¨Ïä§?ä∏
   PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN5 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM9 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM10 FOREIGN KEY(MCODE) REFERENCES  HONEYBEE(MHCODE)
);

CREATE TABLE PLANSPONLIST
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏?ùò ?õÑ?õê?ûê Î¶¨Ïä§?ä∏
    PCODE VARCHAR2(13),
    MCODE VARCHAR2(11),
    CONSTRAINT PK_PROANDMEN6 PRIMARY KEY(PCODE,MCODE),
    CONSTRAINT FK_PROANDMEM11 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE),
    CONSTRAINT FK_PROANDMEM12 FOREIGN KEY(MCODE) REFERENCES  HONEYBEE(MHCODE)
);


--?îÑÎ°úÏ†ù?ä∏?öî?ïΩ-------------------------------------------------------------------------------

CREATE TABLE ENDBRIEF
(--Ï¢ÖÎ£å?êú ?îÑÎ°úÏ†ù?ä∏ ?öî?ïΩ
    PCODE VARCHAR2(13) PRIMARY KEY,
    CONTENT VARCHAR2(200) NOT NULL,
    MAINIMAGE VARCHAR2(100) NOT NULL,
    IMAGE1 VARCHAR2(100), 
    IMAGE2 VARCHAR2(100), 
    IMAGE3 VARCHAR2(100), 
    IMAGE4 VARCHAR2(100), 
    MAINVIDEO VARCHAR2(100) NOT NULL,
    VIDEO1 VARCHAR2(100),
    VIDEO2 VARCHAR2(100),
    CONSTRAINT FK_BRIEF1 FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE)
);

CREATE TABLE CONBRIEF
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏ ?öî?ïΩ
    PCODE VARCHAR2(13) PRIMARY KEY,
    CONTENT VARCHAR2(200) NOT NULL,
    MAINIMAGE VARCHAR2(100) NOT NULL,
    IMAGE1 VARCHAR2(100), 
    IMAGE2 VARCHAR2(100), 
    IMAGE3 VARCHAR2(100), 
    IMAGE4 VARCHAR2(100), 
    MAINVIDEO VARCHAR2(100) NOT NULL,
    VIDEO1 VARCHAR2(100),
    VIDEO2 VARCHAR2(100),
    CONSTRAINT FK_BRIEF2 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE PLANBRIEF
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏ ?öî?ïΩ
    PCODE VARCHAR2(13) PRIMARY KEY,
    CONTENT VARCHAR2(200) NOT NULL,
    MAINIMAGE VARCHAR2(100) NOT NULL,
    IMAGE1 VARCHAR2(100), 
    IMAGE2 VARCHAR2(100), 
    IMAGE3 VARCHAR2(100), 
    IMAGE4 VARCHAR2(100), 
    MAINVIDEO VARCHAR2(100) NOT NULL,
    VIDEO1 VARCHAR2(100),
    VIDEO2 VARCHAR2(100),
    CONSTRAINT FK_BRIEF3 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

--?ûêÏ£ºÎ¨ª?äîÏßàÎ¨∏-------------------------------------------------------------------------------

CREATE TABLE ENDFAQ
(--Ï¢ÖÎ£å?êú ?îÑÎ°úÏ†ù?ä∏ ?ûêÏ£ºÎ¨ª?äîÏßàÎ¨∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    EINDEX NUMBER NOT NULL UNIQUE,
    QUESTION VARCHAR2(100) NOT NULL,
    ANSWER VARCHAR2(100) NOT NULL, 
    CONSTRAINT FK_BRIEFFAQ1 FOREIGN KEY(PCODE) REFERENCES  ENDBRIEF(PCODE)
);

CREATE TABLE CONFAQ
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏ ?ûêÏ£ºÎ¨ª?äîÏßàÎ¨∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    QUESTION VARCHAR2(100) NOT NULL,
    ANSWER VARCHAR2(100) NOT NULL, 
    CONSTRAINT FK_BRIEFFAQ2 FOREIGN KEY(PCODE) REFERENCES CONBRIEF(PCODE)
);

CREATE TABLE PLANFAQ
(--Ï¢ÖÎ£å?êú ?îÑÎ°úÏ†ù?ä∏ ?ûêÏ£ºÎ¨ª?äîÏßàÎ¨∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    PINDEX NUMBER(1) NOT NULL UNIQUE,
    QUESTION VARCHAR2(100) NOT NULL,
    ANSWER VARCHAR2(100) NOT NULL, 
    CONSTRAINT FK_BRIEFFAQ3 FOREIGN KEY(PCODE) REFERENCES  PLANBRIEF(PCODE)
);

--?ù¥Î≤§Ìä∏---------------------------------------------------------------------------

CREATE TABLE ENDEVENT
(--Ï¢ÖÎ£å?êú ?ù¥Î≤§Ìä∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    EINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    CONSTRAINT FK_ENDEVENT FOREIGN KEY(PCODE) REFERENCES  ENDPROJECT(PCODE)
);

CREATE TABLE PLANEVENT
(--?òà?†ï?êú ?ù¥Î≤§Ìä∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    PINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL, 
    CONSTRAINT FK_PLANEVENT FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

CREATE TABLE CONENDEVENT
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò Ï¢ÖÎ£å?êú ?ù¥Î≤§Ìä∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL, 
    CONSTRAINT FK_CONEVENT1 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE CONEVENT
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò ÏßÑÌñâÏ§? ?ù¥Î≤§Ìä∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL, 
    CONSTRAINT FK_CONEVENT2 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE CONPLANEVENT
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò ?òà?†ï?êú ?ù¥Î≤§Ìä∏
    PCODE VARCHAR2(13) PRIMARY KEY,
    CINDEX NUMBER(1) NOT NULL UNIQUE,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    SDATE DATE NOT NULL,
    EDATE DATE NOT NULL,
    CONSTRAINT FK_CONEVENT3 FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

--Í≥µÏ??Ç¨?ï≠---------------------------------------------------------------------------

CREATE TABLE CONNOTICE
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò Í≥µÏ??Ç¨?ï≠ Í≤åÏãú?åê
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_NBOARDPRO FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE PLANNOTICE
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏?ùò Í≥µÏ??Ç¨?ï≠ Í≤åÏãú?åê
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_NBOARDPRO2 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

--?îÑÎ°úÏ†ù?ä∏Í≤åÏãú?åê---------------------------------------------------------------------------

CREATE TABLE CONPBOARD
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò ?îÑÎ°úÏ†ù?ä∏ Í≤åÏãú?åê
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_BOARDPRO FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

--?ûê?ú†Í≤åÏãú?åê---------------------------------------------------------------------------

CREATE TABLE CONFBOARD
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏?ùò ?ûê?ú† Í≤åÏãú?åê
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_FBOARDPRO FOREIGN KEY(PCODE) REFERENCES  CONPROJECT(PCODE)
);

CREATE TABLE PLANFBOARD
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏?ùò ?ûê?ú† Í≤åÏãú?åê
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL, 
    CONSTRAINT FK_FBOARDPRO2 FOREIGN KEY(PCODE) REFERENCES  PLANPROJECT(PCODE)
);

--?Ç≠?†ú?êúÍ∏?---------------------------------------------------------------------------

CREATE TABLE DELETEBOARD
(--?Ç≠?†ú?êú Í≤åÏãúÍ∏? ?ûÑ?ãúÎ≥¥Í?
    BCODE VARCHAR2(11) PRIMARY KEY,
    PCODE VARCHAR2(13),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(300) NOT NULL,
    NDATE DATE NOT NULL,
    WRITER VARCHAR2(11) NOT NULL
);

--Ï≤®Î??åå?ùº---------------------------------------------------------------------------

CREATE TABLE CONNFILE
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏ Í≥µÏ??Ç¨?ï≠ Ï≤®Î??åå?ùº
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_CFILE1 FOREIGN KEY(BCODE) REFERENCES CONNOTICE(BCODE)
);

CREATE TABLE CONPFILE
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏ ?îÑÎ°úÏ†ù?ä∏ Í≤åÏãú?åê Ï≤®Î??åå?ùº
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_CFILE2 FOREIGN KEY(BCODE) REFERENCES  CONPBOARD(BCODE)
);

CREATE TABLE CONFFILE
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏ ?ûê?ú† Í≤åÏãú?åê Ï≤®Î??åå?ùº
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_CFILE3 FOREIGN KEY(BCODE) REFERENCES  CONFBOARD(BCODE)
);

--?òà?†ï------------

CREATE TABLE PLANNFILE
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏ Í≥µÏ??Ç¨?ï≠ Ï≤®Î??åå?ùº
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_PFILE1 FOREIGN KEY(BCODE) REFERENCES  PLANNOTICE(BCODE)
);

CREATE TABLE PLANFFILE
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏ ?ûê?ú† Í≤åÏãú?åê Ï≤®Î??åå?ùº
    BCODE VARCHAR2(11) PRIMARY KEY,
    LINK1 VARCHAR2(1000),
    LINK2 VARCHAR2(1000),
    LINK3 VARCHAR2(1000),
    CONSTRAINT FK_PFILE2 FOREIGN KEY(BCODE) REFERENCES  PLANFBOARD(BCODE)
);

--?åìÍ∏?---------------------------------------------------------------------------

CREATE TABLE CONPCOMMENT
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏ ?îÑÎ°úÏ†ù?ä∏ Í≤åÏãú?åê ?åìÍ∏?
    BCODE VARCHAR2(11),
    CINDEX NUMBER(6),
    TOPINDEX NUMBER(6),
    WRITER VARCHAR2(11),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(300),
    CONSTRAINT PK_COMEN1 PRIMARY KEY(BCODE, CINDEX),
    CONSTRAINT FK_COMEN1 FOREIGN KEY(BCODE) REFERENCES  CONPBOARD(BCODE)
);

CREATE TABLE CONFCOMMENT
(--ÏßÑÌñâÏ§? ?îÑÎ°úÏ†ù?ä∏ ?ûê?ú† Í≤åÏãú?åê ?åìÍ∏?
    BCODE VARCHAR2(11),
    CINDEX NUMBER(6),
    TOPINDEX NUMBER(6),
    WRITER VARCHAR2(11),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(300),
    CONSTRAINT PK_COMEN2 PRIMARY KEY(BCODE, CINDEX),
    CONSTRAINT FK_CCOMEN2 FOREIGN KEY(BCODE) REFERENCES  CONFBOARD(BCODE)
);

CREATE TABLE PLANFCOMMENT
(--?òà?†ï?êú ?îÑÎ°úÏ†ù?ä∏ ?ûê?ú† Í≤åÏãú?åê ?åìÍ∏?
    BCODE VARCHAR2(11),
    CINDEX NUMBER(6),
    TOPINDEX NUMBER(6),
    WRITER VARCHAR2(11),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(300),
    CONSTRAINT PK_COMEN3 PRIMARY KEY(BCODE, CINDEX),
    CONSTRAINT FK_CCOMEN3 FOREIGN KEY(BCODE) REFERENCES  PLANFBOARD(BCODE)
);